In [ ]:
import torch
import torch.nn as nn
import numpy as np
import cv2
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torch.utils.data import Dataset
import torchvision
import torchvision.datasets as datasets
import torchvision.transforms as transforms
import os
import pandas as pd
from skimage import io
from tqdm.notebook import tqdm
import gc

In [ ]:
torch.cuda.empty_cache()
# del variables
# gc.collect()

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

learning_rate = 3e-4
batch_size = 4
num_epochs = 70
# in_channels = 4

cuda


In [ ]:
class LogCoshLoss(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, y_t, y_prime_t):
        ey_t = y_t - y_prime_t
        return torch.mean(torch.log(torch.cosh(ey_t + 1e-12)))

# class Identity(nn.Module):
#   def __init__(self):
#     super(Identity,self).__init__()

#   def forward(self, x):
#     return x

class PrintLayer(nn.Module):
    def __init__(self):
        super(PrintLayer, self).__init__()
    
    def forward(self, x):
        # Do your print / debug stuff here
        print(x)
        return x

In [ ]:
class Rotated_CCS1_CCS2(Dataset):
  def __init__(self, csv_file, root_dir, transform=None):
    self.annotations = pd.read_csv(csv_file)
    self.root_dir = root_dir
    self.transform = transform
  
  def __len__(self):
    return len(self.annotations)

  def __getitem__(self,index):
    img_path = os.path.join(self.root_dir, self.annotations.iloc[index, 0]+'.png')
    image = cv2.imread(img_path)
    y_label = torch.tensor(float(self.annotations.iloc[index, 1]))

    if self.transform:
      image = self.transform(image)
      # print(torch.isnan(data).any())
    return (image, y_label)

In [ ]:
model = torchvision.models.vgg16()
# model.classifier[6] = Linear(in_features = 4096, out_features = 1024, bias=True)
# model.classifier[7] = Softmax(in_features = 1024, out_features = 1)
# for param in model.parameters():
#   param.requires_grad = False
# # model.features[0] = nn.Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
# model.classifier = nn.Sequential(nn.Linear(in_features = 25088, out_features = 4096, bias=True),
#                                  nn.ReLU(inplace=True),
#                                  nn.Dropout(p=0.5, inplace=False),
#                                  nn.Linear(in_features = 4096, out_features = 4096, bias=True),
#                                  nn.ReLU(inplace=True),
#                                  nn.Dropout(p=0.5, inplace=False),
#                                  nn.Linear(in_features = 4096, out_features = 1024, bias=True),
#                                  nn.ReLU(inplace=True),
#                                  nn.Dropout(p=0.5, inplace=False),
#                                  nn.Linear(in_features = 1024, out_features = 1, bias=True),
#                                  nn.Sigmoid())

print(model)

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1

In [ ]:
model.classifier[6] = nn.Linear(in_features=4096, out_features=1, bias=True)

model.classifier = nn.Sequential(
    nn.Linear(in_features=25088, out_features=4096, bias=True),
    PrintLayer(),
    nn.ReLU(inplace=True),
    nn.Dropout(p=0.5, inplace=False),
    nn.Linear(in_features=4096, out_features=4096, bias=True),
    PrintLayer(),
    nn.ReLU(inplace=True),
    nn.Dropout(p=0.5, inplace=False),
    nn.Linear(in_features=4096, out_features=1, bias=True)
)

In [ ]:
# model.classifier = model.classifier[:4] 

In [ ]:
model.to(device)

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1

In [ ]:
# model.avgpool = Identity()
# model.classifier = torch.nn.Sequential(
#     nn.Linear(in_features=512, out_features=128, bias=True),
#     nn.ReLU(inplace=True),
#     nn.Dropout(p=0.5, inplace = True),
#     nn.Linear(in_features=128, out_features=1, bias=True)
#     # torch.nn.Sigmoid()
# )

In [ ]:
# model.to(device)

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
dataset = Rotated_CCS1_CCS2(csv_file='/content/drive/MyDrive/data/rotatedportDegrees.csv', root_dir = '/content/drive/MyDrive/data', transform = transforms.Compose(
    [transforms.ToTensor(),
    torchvision.models.VGG16_Weights.IMAGENET1K_FEATURES.transforms()]))
print(len(dataset))
train_set, test_set = torch.utils.data.random_split(dataset, [0.75, 0.25])
train_loader = DataLoader(dataset=train_set, batch_size=batch_size, shuffle=True, pin_memory=True)
test_loader = DataLoader(dataset =test_set, batch_size=batch_size, shuffle=False, pin_memory=True)

100


In [ ]:
criterion = nn.MSELoss()
# criterion = LogCoshLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)
i = 1
sum = 0
def save_checkpoint(state, filename = "/content/drive/MyDrive/data/saved_model1.pth.tar"):
  print("..Saving Model..")
  torch.save(state, filename)

def load_checkpoint(checkpoint):
    print("..Loading Checkpoint..")
    model.load_state_dict(checkpoint['state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer'])

In [ ]:
for epoch in range (num_epochs):
  sum = 0
  for batch_idx, (data, targets) in enumerate(tqdm(train_loader)):
    data=data.to(device=device, non_blocking=True)
    targets=targets.to(device=device, non_blocking=True)
    targets = targets.reshape(-1, 1)
    scores = model(data)
    print(targets.shape)
    print(scores.shape)
    print(scores, targets)
    loss = torch.sqrt(criterion(scores, targets))
    sum += loss

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
  print(f'loss = {float(sum)/float(len(train_loader)) * 100:.2f}%')
  

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0346, -0.0162, -0.0448,  ..., -0.0321, -0.0132, -0.0103],
        [-0.0275, -0.0145, -0.0511,  ..., -0.0427, -0.0060, -0.0198],
        [-0.0276, -0.0123, -0.0340,  ..., -0.0022, -0.0122, -0.0194],
        [-0.0297, -0.0141, -0.0132,  ...,  0.0031, -0.0103, -0.0209]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0066, -0.0251, -0.0040,  ..., -0.0117,  0.0077, -0.0190],
        [-0.0257, -0.0317, -0.0237,  ..., -0.0173,  0.0147, -0.0272],
        [-0.0349, -0.0181,  0.0244,  ..., -0.0480, -0.0245, -0.0261],
        [-0.0127, -0.0214,  0.0055,  ..., -0.0268, -0.0261, -0.0240]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4421],
        [0.3554],
        [0.9541],
        [0.7580]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4497],
        [0.3833],
        [0.9444],
        [0.6844]], device='cuda:0')
tensor([[-0.0298, -0.0111, -0.0445,  ..., -0.0351, -0.0103, -0.0152],
        [-0.0339, -0.011

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0278, -0.0103, -0.0376,  ..., -0.0277, -0.0070, -0.0136],
        [-0.0287, -0.0130, -0.0438,  ..., -0.0240, -0.0093, -0.0159],
        [-0.0304, -0.0152, -0.0345,  ..., -0.0351, -0.0080, -0.0106],
        [-0.0334, -0.0110, -0.0379,  ..., -0.0309, -0.0079, -0.0145]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0096, -0.0231,  0.0090,  ..., -0.0221, -0.0044, -0.0201],
        [-0.0094, -0.0247,  0.0007,  ..., -0.0137,  0.0095, -0.0193],
        [-0.0079, -0.0212,  0.0050,  ..., -0.0118,  0.0050, -0.0217],
        [-0.0089, -0.0209,  0.0010,  ..., -0.0148,  0.0136, -0.0206]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.6061],
        [0.4850],
        [0.5275],
        [0.4614]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.6722],
        [0.4683],
        [0.5381],
        [0.4489]], device='cuda:0')
tensor([[-0.0248, -0.0102, -0.0177,  ..., -0.0220, -0.0083, -0.0112],
        [-0.0243, -0.009

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0357, -0.0110, -0.0281,  ..., -0.0479, -0.0080, -0.0103],
        [-0.0267, -0.0097, -0.0122,  ..., -0.0186, -0.0085, -0.0103],
        [-0.0362, -0.0110, -0.0422,  ..., -0.0606, -0.0027, -0.0165],
        [-0.0373, -0.0117, -0.0437,  ..., -0.0590, -0.0039, -0.0187]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0060, -0.0231, -0.0001,  ..., -0.0127,  0.0085, -0.0223],
        [-0.0129, -0.0257,  0.0076,  ..., -0.0262, -0.0069, -0.0212],
        [-0.0180, -0.0224, -0.0054,  ..., -0.0190,  0.0121, -0.0241],
        [-0.0250, -0.0299, -0.0188,  ..., -0.0234,  0.0218, -0.0193]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5237],
        [0.6487],
        [0.4125],
        [0.3826]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.5078],
        [0.6569],
        [0.4028],
        [0.3944]], device='cuda:0')
tensor([[-0.0254, -0.0098, -0.0346,  ..., -0.0291, -0.0076, -0.0137],
        [-0.0236, -0.011

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0286, -0.0089, -0.0273,  ..., -0.0130, -0.0058, -0.0142],
        [-0.0214, -0.0097, -0.0145,  ..., -0.0179, -0.0063, -0.0097],
        [-0.0263, -0.0133, -0.0373,  ..., -0.0286, -0.0082, -0.0107],
        [-0.0259, -0.0115, -0.0221,  ..., -0.0172, -0.0044, -0.0140]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0101, -0.0185,  0.0187,  ..., -0.0266, -0.0036, -0.0264],
        [-0.0074, -0.0224,  0.0047,  ..., -0.0168,  0.0012, -0.0215],
        [-0.0118, -0.0258, -0.0074,  ..., -0.0164,  0.0126, -0.0232],
        [-0.0124, -0.0232,  0.0058,  ..., -0.0134, -0.0023, -0.0219]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.7670],
        [0.5475],
        [0.4454],
        [0.5558]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.7083],
        [0.5611],
        [0.4497],
        [0.5861]], device='cuda:0')
tensor([[-0.0211, -0.0139, -0.0250,  ..., -0.0199, -0.0088, -0.0076],
        [-0.0267, -0.011

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0250, -0.0069, -0.0276,  ..., -0.0147, -0.0081, -0.0151],
        [-0.0138, -0.0089, -0.0205,  ..., -0.0040, -0.0076, -0.0117],
        [-0.0163, -0.0096, -0.0139,  ..., -0.0075, -0.0059, -0.0097],
        [-0.0152, -0.0085, -0.0240,  ..., -0.0126, -0.0055, -0.0092]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0232, -0.0221,  0.0210,  ..., -0.0301, -0.0149, -0.0291],
        [-0.0239, -0.0254,  0.0235,  ..., -0.0310, -0.0190, -0.0218],
        [-0.0162, -0.0245,  0.0049,  ..., -0.0173,  0.0040, -0.0239],
        [-0.0116, -0.0222,  0.0052,  ..., -0.0148,  0.0028, -0.0210]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.7646],
        [0.7830],
        [0.5341],
        [0.4819]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.8167],
        [0.9472],
        [0.5611],
        [0.5222]], device='cuda:0')
tensor([[-0.0160, -0.0086, -0.0245,  ..., -0.0122, -0.0058, -0.0091],
        [-0.0206, -0.008

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0244, -0.0088, -0.0350,  ..., -0.0271, -0.0071, -0.0122],
        [-0.0198, -0.0114, -0.0371,  ..., -0.0320, -0.0061, -0.0170],
        [-0.0250, -0.0108, -0.0242,  ..., -0.0082, -0.0074, -0.0165],
        [-0.0162, -0.0099, -0.0312,  ..., -0.0199, -0.0076, -0.0189]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0075, -0.0214,  0.0075,  ..., -0.0140,  0.0042, -0.0215],
        [-0.0192, -0.0261, -0.0040,  ..., -0.0171,  0.0188, -0.0223],
        [-0.0333, -0.0264,  0.0286,  ..., -0.0375, -0.0228, -0.0293],
        [-0.0195, -0.0298, -0.0080,  ..., -0.0237,  0.0268, -0.0275]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5129],
        [0.3856],
        [0.7854],
        [0.2664]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.5094],
        [0.3361],
        [0.8722],
        [0.2750]], device='cuda:0')
tensor([[-0.0172, -0.0092, -0.0274,  ..., -0.0212, -0.0066, -0.0110],
        [-0.0239, -0.009

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0263, -0.0097, -0.0286,  ..., -0.0195, -0.0078, -0.0210],
        [-0.0310, -0.0070, -0.0471,  ..., -0.0471, -0.0080, -0.0292],
        [-0.0308, -0.0113, -0.0417,  ..., -0.0449, -0.0088, -0.0133],
        [-0.0276, -0.0100, -0.0340,  ..., -0.0390, -0.0082, -0.0138]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0223, -0.0271,  0.0274,  ..., -0.0243, -0.0135, -0.0259],
        [-0.0358, -0.0537, -0.0295,  ..., -0.0207,  0.0668, -0.0254],
        [-0.0097, -0.0235,  0.0086,  ..., -0.0142,  0.0123, -0.0232],
        [-0.0079, -0.0212,  0.0097,  ..., -0.0112,  0.0039, -0.0209]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.7883],
        [0.0710],
        [0.4763],
        [0.5008]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.7500],
        [0.0694],
        [0.4806],
        [0.5178]], device='cuda:0')
tensor([[-0.0321, -0.0104, -0.0379,  ..., -0.0420, -0.0089, -0.0148],
        [-0.0349, -0.012

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0249, -0.0093, -0.0431,  ..., -0.0382, -0.0082, -0.0113],
        [-0.0195, -0.0132, -0.0377,  ..., -0.0393, -0.0078, -0.0194],
        [-0.0198, -0.0112, -0.0209,  ..., -0.0052, -0.0075, -0.0140],
        [-0.0260, -0.0130, -0.0296,  ..., -0.0278, -0.0075, -0.0081]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0084, -0.0222,  0.0084,  ..., -0.0121,  0.0063, -0.0199],
        [-0.0163, -0.0301,  0.0011,  ..., -0.0193,  0.0196, -0.0258],
        [-0.0181, -0.0304,  0.0219,  ..., -0.0202, -0.0074, -0.0253],
        [-0.0084, -0.0222,  0.0147,  ..., -0.0138,  0.0056, -0.0215]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5121],
        [0.3322],
        [0.6550],
        [0.5409]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.5142],
        [0.3417],
        [0.6806],
        [0.5381]], device='cuda:0')
tensor([[-1.9309e-02, -8.7786e-03, -1.5890e-02,  ..., -1.2844e-02,
         -7.9642e-03, -1.14

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0250, -0.0097, -0.0323,  ..., -0.0265, -0.0087, -0.0120],
        [-0.0276, -0.0094, -0.0309,  ..., -0.0408, -0.0093, -0.0116],
        [-0.0192, -0.0104, -0.0139,  ..., -0.0136, -0.0079, -0.0073],
        [-0.0258, -0.0098, -0.0248,  ..., -0.0044, -0.0056, -0.0157]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0063, -0.0228,  0.0104,  ..., -0.0127,  0.0096, -0.0191],
        [-0.0151, -0.0227,  0.0104,  ..., -0.0134, -0.0063, -0.0133],
        [-0.0110, -0.0218,  0.0133,  ..., -0.0168, -0.0044, -0.0219],
        [-0.0215, -0.0287,  0.0317,  ..., -0.0317, -0.0194, -0.0220]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4997],
        [0.6069],
        [0.6165],
        [0.8363]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4739],
        [0.6028],
        [0.6569],
        [0.8306]], device='cuda:0')
tensor([[-0.0260, -0.0120, -0.0293,  ..., -0.0354, -0.0084, -0.0088],
        [-0.0214, -0.008

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0193, -0.0105, -0.0192,  ..., -0.0144, -0.0060, -0.0138],
        [-0.0227, -0.0084, -0.0347,  ..., -0.0317, -0.0084, -0.0142],
        [-0.0219, -0.0097, -0.0197,  ..., -0.0174, -0.0057, -0.0168],
        [-0.0171, -0.0086, -0.0146,  ..., -0.0070, -0.0075, -0.0127]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0073, -0.0231,  0.0094,  ..., -0.0151,  0.0034, -0.0199],
        [-0.0069, -0.0218,  0.0101,  ..., -0.0133,  0.0081, -0.0196],
        [-0.0067, -0.0238,  0.0111,  ..., -0.0152,  0.0063, -0.0208],
        [-0.0117, -0.0243,  0.0182,  ..., -0.0238, -0.0163, -0.0226]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5471],
        [0.5172],
        [0.5173],
        [0.7170]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.5103],
        [0.5278],
        [0.4972],
        [0.7167]], device='cuda:0')
tensor([[-0.0244, -0.0131, -0.0393,  ..., -0.0210, -0.0093, -0.0137],
        [-0.0293, -0.012

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0209, -0.0088, -0.0293,  ..., -0.0332, -0.0080, -0.0120],
        [-0.0311, -0.0095, -0.0324,  ..., -0.0178, -0.0077, -0.0129],
        [-0.0390, -0.0078, -0.0189,  ..., -0.0676, -0.0134, -0.0120],
        [-0.0348, -0.0077, -0.0303,  ..., -0.0454, -0.0080, -0.0141]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0291, -0.0334, -0.0020,  ..., -0.0186,  0.0375, -0.0233],
        [-0.0203, -0.0196,  0.0262,  ..., -0.0226, -0.0129, -0.0242],
        [-0.0202, -0.0288,  0.0226,  ..., -0.0189, -0.0226, -0.0137],
        [-0.0144, -0.0230,  0.0051,  ..., -0.0138,  0.0143, -0.0202]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.2752],
        [0.6908],
        [0.6868],
        [0.4490]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.2556],
        [0.7083],
        [0.6278],
        [0.4247]], device='cuda:0')
tensor([[-0.0321, -0.0121, -0.0272,  ..., -0.0561, -0.0111, -0.0058],
        [-0.0292, -0.011

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0342, -0.0124, -0.0154,  ..., -0.0118, -0.0169, -0.0108],
        [-0.0317, -0.0095, -0.0336,  ..., -0.0287, -0.0119, -0.0153],
        [-0.0378, -0.0078, -0.0252,  ..., -0.0477, -0.0195, -0.0105],
        [-0.0341, -0.0120, -0.0429,  ..., -0.0607, -0.0195, -0.0121]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0157, -0.0288,  0.0172,  ..., -0.0159, -0.0192, -0.0231],
        [-0.0125, -0.0216,  0.0115,  ..., -0.0128, -0.0072, -0.0232],
        [-0.0094, -0.0226,  0.0157,  ..., -0.0130, -0.0117, -0.0164],
        [-0.0152, -0.0224,  0.0087,  ..., -0.0187,  0.0149, -0.0225]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.6594],
        [0.5895],
        [0.6190],
        [0.4027]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.6669],
        [0.5569],
        [0.6278],
        [0.4028]], device='cuda:0')
tensor([[-0.0310, -0.0082, -0.0430,  ..., -0.0351, -0.0168, -0.0102],
        [-0.0342, -0.014

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0257, -0.0121, -0.0153,  ..., -0.0103, -0.0161, -0.0114],
        [-0.0419, -0.0089, -0.0278,  ..., -0.0547, -0.0229, -0.0152],
        [-0.0314, -0.0128, -0.0220,  ..., -0.0193, -0.0161, -0.0108],
        [-0.0314, -0.0097, -0.0425,  ..., -0.0464, -0.0182, -0.0108]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0151, -0.0189,  0.0259,  ..., -0.0236, -0.0200, -0.0264],
        [-0.0104, -0.0207,  0.0213,  ..., -0.0086, -0.0195, -0.0226],
        [-0.0171, -0.0216,  0.0219,  ..., -0.0157, -0.0120, -0.0246],
        [-0.0111, -0.0206,  0.0088,  ..., -0.0140,  0.0068, -0.0220]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.7566],
        [0.5941],
        [0.6445],
        [0.4216]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.6844],
        [0.6278],
        [0.6250],
        [0.4247]], device='cuda:0')
tensor([[-0.0287, -0.0116, -0.0335,  ..., -0.0084, -0.0175, -0.0119],
        [-0.0298, -0.013

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0279, -0.0125, -0.0292,  ..., -0.0429, -0.0164, -0.0060],
        [-0.0168, -0.0138, -0.0376,  ..., -0.0292, -0.0155, -0.0150],
        [-0.0256, -0.0115, -0.0328,  ..., -0.0276, -0.0174, -0.0121],
        [-0.0206, -0.0133, -0.0240,  ..., -0.0110, -0.0139, -0.0129]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0083, -0.0214,  0.0143,  ..., -0.0119,  0.0035, -0.0221],
        [-0.0204, -0.0301, -0.0080,  ..., -0.0145,  0.0135, -0.0225],
        [-0.0071, -0.0218,  0.0125,  ..., -0.0129,  0.0084, -0.0215],
        [-0.0101, -0.0167,  0.0178,  ..., -0.0169, -0.0074, -0.0208]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5342],
        [0.3405],
        [0.5238],
        [0.5900]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.5056],
        [0.3417],
        [0.4861],
        [0.5861]], device='cuda:0')
tensor([[-0.0243, -0.0114, -0.0401,  ..., -0.0343, -0.0165, -0.0132],
        [-0.0278, -0.011

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0261, -0.0114, -0.0512,  ..., -0.0539, -0.0198, -0.0131],
        [-0.0187, -0.0125, -0.0207,  ...,  0.0002, -0.0158, -0.0142],
        [-0.0239, -0.0100, -0.0385,  ..., -0.0280, -0.0183, -0.0119],
        [-0.0262, -0.0129, -0.0471,  ..., -0.0416, -0.0193, -0.0128]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0121, -0.0229,  0.0074,  ..., -0.0128,  0.0114, -0.0218],
        [-0.0209, -0.0224,  0.0257,  ..., -0.0213, -0.0162, -0.0282],
        [-0.0073, -0.0259,  0.0120,  ..., -0.0140,  0.0011, -0.0241],
        [-0.0071, -0.0238,  0.0110,  ..., -0.0126,  0.0163, -0.0209]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.3954],
        [0.7289],
        [0.5641],
        [0.4570]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4247],
        [0.6806],
        [0.5278],
        [0.4861]], device='cuda:0')
tensor([[-0.0225, -0.0137, -0.0276,  ..., -0.0173, -0.0136, -0.0154],
        [-0.0348, -0.013

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0221, -0.0128, -0.0406,  ..., -0.0210, -0.0148, -0.0131],
        [-0.0211, -0.0100, -0.0475,  ..., -0.0405, -0.0202, -0.0197],
        [-0.0189, -0.0097, -0.0359,  ..., -0.0246, -0.0130, -0.0197],
        [-0.0203, -0.0099, -0.0337,  ..., -0.0175, -0.0165, -0.0114]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0131, -0.0337,  0.0026,  ..., -0.0169,  0.0156, -0.0214],
        [-0.0267, -0.0348, -0.0083,  ..., -0.0185,  0.0214, -0.0289],
        [-0.0177, -0.0271,  0.0033,  ..., -0.0150,  0.0162, -0.0227],
        [-0.0103, -0.0263,  0.0137,  ..., -0.0136,  0.0042, -0.0208]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4230],
        [0.3321],
        [0.3625],
        [0.5464]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4333],
        [0.3750],
        [0.2750],
        [0.5278]], device='cuda:0')
tensor([[-0.0203, -0.0095, -0.0395,  ..., -0.0245, -0.0167, -0.0141],
        [-0.0190, -0.010

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0153, -0.0105, -0.0288,  ..., -0.0274, -0.0177, -0.0144],
        [-0.0124, -0.0121, -0.0358,  ..., -0.0408, -0.0160, -0.0189],
        [-0.0266, -0.0129, -0.0103,  ..., -0.0018, -0.0159, -0.0162],
        [-0.0283, -0.0134, -0.0380,  ..., -0.0680, -0.0216, -0.0057]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0061, -0.0205,  0.0134,  ..., -0.0153,  0.0075, -0.0225],
        [-0.0279, -0.0356, -0.0126,  ..., -0.0197,  0.0302, -0.0303],
        [-0.0252, -0.0272,  0.0256,  ..., -0.0262, -0.0085, -0.0276],
        [-0.0069, -0.0225,  0.0107,  ..., -0.0145,  0.0116, -0.0217]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4990],
        [0.3772],
        [0.7656],
        [0.5043]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.5344],
        [0.3642],
        [0.6669],
        [0.5158]], device='cuda:0')
tensor([[-0.0129, -0.0097, -0.0159,  ..., -0.0050, -0.0144, -0.0152],
        [-0.0106, -0.010

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0142, -0.0104, -0.0291,  ..., -0.0241, -0.0160, -0.0114],
        [-0.0179, -0.0107, -0.0303,  ..., -0.0208, -0.0129, -0.0148],
        [-0.0126, -0.0118, -0.0301,  ..., -0.0288, -0.0154, -0.0146],
        [-0.0143, -0.0095, -0.0295,  ..., -0.0085, -0.0169, -0.0120]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0057, -0.0219,  0.0115,  ..., -0.0134,  0.0117, -0.0210],
        [-0.0093, -0.0206,  0.0150,  ..., -0.0149,  0.0058, -0.0223],
        [-0.0151, -0.0279, -0.0015,  ..., -0.0144,  0.0196, -0.0235],
        [-0.0269, -0.0262,  0.0409,  ..., -0.0316, -0.0195, -0.0394]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5058],
        [0.5622],
        [0.3841],
        [0.8980]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4861],
        [0.5569],
        [0.3642],
        [0.9417]], device='cuda:0')
tensor([[-0.0182, -0.0080, -0.0245,  ..., -0.0443, -0.0190, -0.0141],
        [-0.0154, -0.009

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0170, -0.0153, -0.0460,  ..., -0.0335, -0.0182, -0.0098],
        [-0.0245, -0.0114, -0.0327,  ..., -0.0340, -0.0165, -0.0203],
        [-0.0167, -0.0123, -0.0323,  ..., -0.0518, -0.0201, -0.0072],
        [-0.0121, -0.0142, -0.0290,  ..., -0.0297, -0.0158, -0.0096]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0193, -0.0319, -0.0069,  ..., -0.0175,  0.0180, -0.0226],
        [-0.0166, -0.0228,  0.0151,  ..., -0.0180, -0.0049, -0.0283],
        [-0.0068, -0.0228,  0.0112,  ..., -0.0131,  0.0120, -0.0240],
        [-0.0070, -0.0201,  0.0125,  ..., -0.0128,  0.0084, -0.0223]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.3946],
        [0.6721],
        [0.5166],
        [0.5261]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4333],
        [0.7083],
        [0.5056],
        [0.5381]], device='cuda:0')
tensor([[-0.0103, -0.0098, -0.0283,  ...,  0.0008, -0.0191, -0.0171],
        [-0.0116, -0.012

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0023, -0.0112, -0.0324,  ..., -0.0329, -0.0155, -0.0104],
        [-0.0019, -0.0122, -0.0356,  ..., -0.0293, -0.0143, -0.0131],
        [-0.0066, -0.0108, -0.0297,  ..., -0.0369, -0.0157, -0.0079],
        [-0.0057, -0.0103, -0.0186,  ..., -0.0166, -0.0154, -0.0132]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0105, -0.0248,  0.0086,  ..., -0.0135,  0.0157, -0.0217],
        [-0.0151, -0.0355, -0.0097,  ..., -0.0179,  0.0114, -0.0245],
        [-0.0072, -0.0218,  0.0085,  ..., -0.0125,  0.0120, -0.0230],
        [-0.0307, -0.0322,  0.0252,  ..., -0.0310, -0.0346, -0.0298]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4695],
        [0.3670],
        [0.5054],
        [0.9324]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4172],
        [0.3361],
        [0.5056],
        [0.9861]], device='cuda:0')
tensor([[-0.0050, -0.0113, -0.0216,  ..., -0.0252, -0.0148, -0.0154],
        [-0.0026, -0.010

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0112, -0.0090, -0.0324,  ..., -0.0197, -0.0131, -0.0153],
        [-0.0112, -0.0121, -0.0376,  ..., -0.0284, -0.0156, -0.0087],
        [-0.0132, -0.0120, -0.0332,  ..., -0.0284, -0.0138, -0.0161],
        [-0.0125, -0.0131, -0.0391,  ..., -0.0259, -0.0132, -0.0112]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0187, -0.0241,  0.0401,  ..., -0.0258, -0.0003, -0.0199],
        [-0.0098, -0.0242,  0.0097,  ..., -0.0154,  0.0192, -0.0221],
        [-0.0093, -0.0220,  0.0120,  ..., -0.0138,  0.0073, -0.0222],
        [-0.0079, -0.0214,  0.0141,  ..., -0.0151,  0.0137, -0.0222]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.7759],
        [0.4590],
        [0.5414],
        [0.5142]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.8167],
        [0.4247],
        [0.5569],
        [0.5094]], device='cuda:0')
tensor([[-0.0082, -0.0123, -0.0342,  ..., -0.0119, -0.0153, -0.0163],
        [-0.0093, -0.013

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0146, -0.0101, -0.0389,  ..., -0.0553, -0.0203, -0.0186],
        [-0.0180, -0.0133, -0.0394,  ..., -0.0503, -0.0185, -0.0089],
        [-0.0148, -0.0116, -0.0326,  ..., -0.0458, -0.0169, -0.0212],
        [ 0.0058, -0.0130, -0.0502,  ..., -0.0592, -0.0166, -0.0329]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0060, -0.0220,  0.0141,  ..., -0.0130,  0.0108, -0.0231],
        [-0.0068, -0.0223,  0.0039,  ..., -0.0143,  0.0135, -0.0224],
        [-0.0154, -0.0226,  0.0267,  ..., -0.0165, -0.0186, -0.0309],
        [-0.0329, -0.0406, -0.0590,  ..., -0.0253,  0.0395, -0.0377]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5243],
        [0.5070],
        [0.6408],
        [0.3221]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.5142],
        [0.4683],
        [0.6061],
        [0.2750]], device='cuda:0')
tensor([[-0.0150, -0.0107, -0.0415,  ..., -0.0470, -0.0186, -0.0226],
        [-0.0151, -0.011

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0039, -0.0097, -0.0233,  ..., -0.0058, -0.0136, -0.0122],
        [-0.0090, -0.0116, -0.0139,  ..., -0.0213, -0.0143, -0.0087],
        [-0.0099, -0.0112, -0.0176,  ..., -0.0175, -0.0142, -0.0117],
        [-0.0097, -0.0141, -0.0262,  ..., -0.0279, -0.0138, -0.0111]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-1.6290e-02, -2.6806e-02,  4.5788e-02,  ..., -2.6467e-02,
          6.6856e-04, -2.6093e-02],
        [-1.3590e-02, -2.0658e-02,  2.0404e-02,  ..., -2.0564e-02,
          6.2334e-05, -2.6982e-02],
        [-7.1806e-03, -2.1828e-02,  1.8206e-02,  ..., -1.6181e-02,
          8.2369e-03, -2.3916e-02],
        [-5.6371e-03, -2.2448e-02,  1.6396e-02,  ..., -1.2404e-02,
          1.0179e-02, -2.2398e-02]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.7925],
        [0.6417],
        [0.5722],
        [0.5444]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.9444],
        [0.6569],
        [0.5806],
     

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0127, -0.0114, -0.0372,  ..., -0.0403, -0.0175, -0.0116],
        [-0.0150, -0.0131, -0.0278,  ..., -0.0387, -0.0156, -0.0106],
        [-0.0090, -0.0112, -0.0411,  ..., -0.0480, -0.0192, -0.0145],
        [-0.0143, -0.0121, -0.0360,  ..., -0.0596, -0.0180, -0.0086]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0122, -0.0264,  0.0052,  ..., -0.0139,  0.0201, -0.0245],
        [-0.0081, -0.0237,  0.0068,  ..., -0.0145,  0.0148, -0.0199],
        [-0.0246, -0.0357, -0.0165,  ..., -0.0263,  0.0313, -0.0275],
        [-0.0045, -0.0206,  0.0104,  ..., -0.0129,  0.0145, -0.0262]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.3824],
        [0.4794],
        [0.2377],
        [0.5149]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4172],
        [0.4692],
        [0.2556],
        [0.5078]], device='cuda:0')
tensor([[-0.0197, -0.0152, -0.0302,  ..., -0.0769, -0.0232, -0.0130],
        [-0.0118, -0.011

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0063, -0.0094, -0.0272,  ..., -0.0150, -0.0129, -0.0168],
        [-0.0072, -0.0136, -0.0322,  ..., -0.0348, -0.0132, -0.0179],
        [-0.0171, -0.0089, -0.0289,  ..., -0.0212, -0.0133, -0.0175],
        [-0.0036, -0.0120, -0.0351,  ..., -0.0332, -0.0152, -0.0180]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0103, -0.0328,  0.0254,  ..., -0.0213, -0.0099, -0.0286],
        [-0.0202, -0.0296, -0.0157,  ..., -0.0220,  0.0241, -0.0323],
        [-0.0213, -0.0274,  0.0329,  ..., -0.0228, -0.0068, -0.0247],
        [-0.0269, -0.0386, -0.0227,  ..., -0.0174,  0.0408, -0.0233]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.6694],
        [0.3536],
        [0.7536],
        [0.2611]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.7611],
        [0.3417],
        [0.8167],
        [0.2750]], device='cuda:0')
tensor([[-0.0109, -0.0162, -0.0454,  ..., -0.0538, -0.0142, -0.0162],
        [-0.0189, -0.011

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0102, -0.0104, -0.0285,  ..., -0.0359, -0.0176, -0.0141],
        [-0.0120, -0.0114, -0.0318,  ..., -0.0374, -0.0190, -0.0137],
        [-0.0217, -0.0144, -0.0244,  ..., -0.0403, -0.0156, -0.0138],
        [-0.0195, -0.0136, -0.0359,  ..., -0.0479, -0.0139, -0.0239]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0058, -0.0212,  0.0093,  ..., -0.0130,  0.0079, -0.0203],
        [-0.0078, -0.0225,  0.0111,  ..., -0.0133,  0.0079, -0.0227],
        [-0.0114, -0.0229,  0.0004,  ..., -0.0184,  0.0166, -0.0230],
        [-0.0088, -0.0208,  0.0145,  ..., -0.0114,  0.0021, -0.0212]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5144],
        [0.5080],
        [0.4266],
        [0.5727]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.5178],
        [0.5278],
        [0.4753],
        [0.5569]], device='cuda:0')
tensor([[-0.0009, -0.0096, -0.0326,  ..., -0.0423, -0.0202, -0.0202],
        [-0.0142, -0.015

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0138, -0.0107, -0.0314,  ..., -0.0263, -0.0159, -0.0139],
        [-0.0053, -0.0127, -0.0355,  ..., -0.0331, -0.0129, -0.0122],
        [-0.0084, -0.0104, -0.0168,  ..., -0.0122, -0.0131, -0.0092],
        [-0.0137, -0.0110, -0.0311,  ..., -0.0280, -0.0161, -0.0131]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0114, -0.0263,  0.0043,  ..., -0.0147,  0.0196, -0.0240],
        [-0.0248, -0.0294, -0.0133,  ..., -0.0166,  0.0216, -0.0201],
        [-0.0103, -0.0218,  0.0121,  ..., -0.0168,  0.0071, -0.0238],
        [-0.0075, -0.0234,  0.0053,  ..., -0.0139,  0.0127, -0.0239]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4644],
        [0.3982],
        [0.5206],
        [0.4799]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4531],
        [0.3833],
        [0.5611],
        [0.4806]], device='cuda:0')
tensor([[ 0.0295, -0.0103, -0.0391,  ..., -0.0448, -0.0207, -0.0186],
        [-0.0057, -0.010

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0191, -0.0113, -0.0369,  ..., -0.0370, -0.0136, -0.0097],
        [-0.0236, -0.0115, -0.0319,  ..., -0.0382, -0.0166, -0.0137],
        [-0.0130, -0.0093, -0.0280,  ..., -0.0319, -0.0158, -0.0121],
        [-0.0177, -0.0110, -0.0289,  ..., -0.0424, -0.0153, -0.0067]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0195, -0.0255, -0.0105,  ..., -0.0175,  0.0178, -0.0228],
        [-0.0093, -0.0232,  0.0029,  ..., -0.0170,  0.0137, -0.0210],
        [-0.0055, -0.0217,  0.0088,  ..., -0.0147,  0.0033, -0.0227],
        [-0.0054, -0.0207,  0.0076,  ..., -0.0145,  0.0116, -0.0219]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4204],
        [0.4669],
        [0.5676],
        [0.5135]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4333],
        [0.4739],
        [0.5222],
        [0.5158]], device='cuda:0')
tensor([[-0.0197, -0.0111, -0.0317,  ..., -0.0279, -0.0130, -0.0098],
        [-0.0144, -0.010

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0104, -0.0103, -0.0371,  ..., -0.0426, -0.0183, -0.0115],
        [-0.0183, -0.0106, -0.0360,  ..., -0.0404, -0.0179, -0.0120],
        [-0.0146, -0.0099, -0.0168,  ..., -0.0254, -0.0141, -0.0141],
        [-0.0244, -0.0101, -0.0337,  ..., -0.0498, -0.0189, -0.0150]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0089, -0.0228,  0.0098,  ..., -0.0134,  0.0083, -0.0232],
        [-0.0053, -0.0210,  0.0083,  ..., -0.0143,  0.0108, -0.0217],
        [-0.0072, -0.0208,  0.0101,  ..., -0.0135,  0.0030, -0.0221],
        [-0.0093, -0.0193,  0.0054,  ..., -0.0140,  0.0132, -0.0230]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5912],
        [0.5366],
        [0.5747],
        [0.4704]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.5278],
        [0.4861],
        [0.5103],
        [0.4489]], device='cuda:0')
tensor([[ 0.0290, -0.0133, -0.0476,  ..., -0.0641, -0.0230, -0.0168],
        [-0.0092, -0.009

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0074, -0.0089, -0.0271,  ..., -0.0297, -0.0128, -0.0187],
        [-0.0165, -0.0134, -0.0307,  ..., -0.0364, -0.0137, -0.0127],
        [-0.0105, -0.0128, -0.0285,  ..., -0.0359, -0.0158, -0.0178],
        [-0.0157, -0.0090, -0.0310,  ..., -0.0249, -0.0127, -0.0103]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0130, -0.0204,  0.0140,  ..., -0.0183, -0.0120, -0.0238],
        [-0.0086, -0.0196,  0.0130,  ..., -0.0141,  0.0049, -0.0227],
        [-0.0157, -0.0307, -0.0135,  ..., -0.0129,  0.0126, -0.0230],
        [-0.0074, -0.0209,  0.0082,  ..., -0.0119,  0.0083, -0.0207]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.6196],
        [0.5796],
        [0.3985],
        [0.5435]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.6722],
        [0.5381],
        [0.3417],
        [0.5000]], device='cuda:0')
tensor([[-0.0126, -0.0101, -0.0199,  ..., -0.0205, -0.0151, -0.0155],
        [-0.0107, -0.007

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0135, -0.0104, -0.0132,  ..., -0.0179, -0.0124, -0.0070],
        [-0.0117, -0.0090, -0.0276,  ..., -0.0268, -0.0149, -0.0109],
        [-0.0122, -0.0095, -0.0273,  ..., -0.0166, -0.0143, -0.0077],
        [-0.0101, -0.0075, -0.0265,  ..., -0.0180, -0.0132, -0.0148]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0154, -0.0248,  0.0233,  ..., -0.0234, -0.0050, -0.0227],
        [-0.0296, -0.0300, -0.0098,  ..., -0.0198,  0.0282, -0.0288],
        [-0.0064, -0.0225,  0.0108,  ..., -0.0139,  0.0041, -0.0207],
        [-0.0164, -0.0233,  0.0277,  ..., -0.0284, -0.0283, -0.0241]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.6694],
        [0.2456],
        [0.5723],
        [0.8221]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.6569],
        [0.2556],
        [0.5639],
        [0.8167]], device='cuda:0')
tensor([[-0.0142, -0.0115, -0.0238,  ..., -0.0431, -0.0158, -0.0104],
        [-0.0103, -0.009

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0086, -0.0076, -0.0399,  ..., -0.0412, -0.0168, -0.0260],
        [-0.0104, -0.0126, -0.0548,  ..., -0.0467, -0.0191, -0.0190],
        [-0.0087, -0.0096, -0.0343,  ..., -0.0303, -0.0153, -0.0126],
        [-0.0115, -0.0094, -0.0163,  ..., -0.0128, -0.0134, -0.0118]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0258, -0.0572, -0.0278,  ..., -0.0221,  0.0616, -0.0286],
        [-0.0451, -0.0442, -0.0115,  ..., -0.0254,  0.0774, -0.0133],
        [-0.0078, -0.0211,  0.0091,  ..., -0.0122,  0.0099, -0.0210],
        [-0.0137, -0.0284,  0.0208,  ..., -0.0237, -0.0139, -0.0271]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.0823],
        [0.0830],
        [0.4778],
        [0.6462]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.0694],
        [0.0917],
        [0.5222],
        [0.7167]], device='cuda:0')
tensor([[-0.0127, -0.0103, -0.0227,  ..., -0.0255, -0.0141, -0.0164],
        [-0.0069, -0.009

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0134, -0.0109, -0.0161,  ..., -0.0199, -0.0136, -0.0092],
        [-0.0129, -0.0095, -0.0169,  ..., -0.0494, -0.0185, -0.0167],
        [-0.0020, -0.0119, -0.0414,  ..., -0.0635, -0.0174, -0.0173],
        [-0.0163, -0.0098, -0.0221,  ..., -0.0100, -0.0134, -0.0156]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0131, -0.0220,  0.0122,  ..., -0.0219, -0.0012, -0.0241],
        [-0.0156, -0.0229,  0.0137,  ..., -0.0169, -0.0200, -0.0237],
        [-0.0183, -0.0341, -0.0070,  ..., -0.0171,  0.0133, -0.0238],
        [-0.0203, -0.0276,  0.0357,  ..., -0.0263, -0.0198, -0.0309]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5846],
        [0.6294],
        [0.3820],
        [0.8775]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.6569],
        [0.6278],
        [0.4028],
        [0.8306]], device='cuda:0')
tensor([[-0.0199, -0.0116, -0.0294,  ..., -0.0254, -0.0114, -0.0141],
        [-0.0162, -0.010

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0136, -0.0113, -0.0393,  ..., -0.0467, -0.0171, -0.0164],
        [-0.0239, -0.0145, -0.0339,  ..., -0.0694, -0.0197, -0.0138],
        [-0.0155, -0.0130, -0.0131,  ..., -0.0219, -0.0168, -0.0138],
        [-0.0076, -0.0103, -0.0379,  ..., -0.0439, -0.0184, -0.0182]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-1.1988e-02, -2.5048e-02,  4.2635e-03,  ..., -1.6408e-02,
          1.3349e-02, -2.1788e-02],
        [-1.9971e-02, -2.6416e-02, -3.6224e-03,  ..., -1.6956e-02,
          1.4176e-02, -1.9955e-02],
        [-1.8085e-02, -2.5332e-02,  1.7173e-02,  ..., -1.8864e-02,
          4.5759e-05, -2.4271e-02],
        [-1.3907e-02, -2.3265e-02,  1.9539e-03,  ..., -1.8496e-02,
          1.2300e-02, -2.4027e-02]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4444],
        [0.3896],
        [0.6610],
        [0.4663]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4747],
        [0.4456],
        [0.6669],
     

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0066, -0.0098, -0.0250,  ..., -0.0169, -0.0157, -0.0178],
        [-0.0275, -0.0145, -0.0372,  ..., -0.0752, -0.0194, -0.0131],
        [-0.0097, -0.0109, -0.0240,  ..., -0.0182, -0.0169, -0.0167],
        [-0.0202, -0.0116, -0.0192,  ..., -0.0365, -0.0169, -0.0190]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0186, -0.0202,  0.0323,  ..., -0.0252, -0.0215, -0.0212],
        [-0.0175, -0.0225,  0.0009,  ..., -0.0156,  0.0120, -0.0205],
        [-0.0199, -0.0278,  0.0289,  ..., -0.0254, -0.0147, -0.0245],
        [-0.0067, -0.0221,  0.0089,  ..., -0.0143,  0.0127, -0.0203]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.8036],
        [0.4361],
        [0.8592],
        [0.5193]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.7500],
        [0.4456],
        [0.9472],
        [0.4972]], device='cuda:0')
tensor([[-0.0117, -0.0146, -0.0258,  ..., -0.0399, -0.0193, -0.0148],
        [ 0.0308, -0.012

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0176, -0.0118, -0.0387,  ..., -0.0391, -0.0149, -0.0142],
        [-0.0169, -0.0112, -0.0291,  ..., -0.0409, -0.0173, -0.0099],
        [-0.0171, -0.0123, -0.0248,  ..., -0.0388, -0.0167, -0.0210],
        [-0.0182, -0.0129, -0.0122,  ..., -0.0248, -0.0171, -0.0176]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0193, -0.0317, -0.0116,  ..., -0.0196,  0.0163, -0.0261],
        [-0.0057, -0.0207,  0.0089,  ..., -0.0135,  0.0114, -0.0214],
        [-0.0088, -0.0221,  0.0022,  ..., -0.0137,  0.0163, -0.0228],
        [-0.0186, -0.0231,  0.0147,  ..., -0.0152, -0.0190, -0.0225]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4061],
        [0.5275],
        [0.4365],
        [0.6785]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.3833],
        [0.5158],
        [0.4611],
        [0.6844]], device='cuda:0')
tensor([[-0.0107, -0.0095, -0.0212,  ..., -0.0194, -0.0151, -0.0192],
        [-0.0191, -0.009

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0257, -0.0105, -0.0260,  ..., -0.0289, -0.0132, -0.0149],
        [-0.0141, -0.0096, -0.0297,  ..., -0.0213, -0.0151, -0.0121],
        [-0.0198, -0.0099, -0.0270,  ..., -0.0192, -0.0124, -0.0146],
        [-0.0263, -0.0106, -0.0289,  ..., -0.0357, -0.0138, -0.0122]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0066, -0.0182,  0.0105,  ..., -0.0140,  0.0045, -0.0197],
        [-0.0063, -0.0218,  0.0065,  ..., -0.0141,  0.0124, -0.0224],
        [-0.0153, -0.0241,  0.0118,  ..., -0.0234, -0.0060, -0.0264],
        [-0.0070, -0.0217,  0.0070,  ..., -0.0145,  0.0128, -0.0219]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5361],
        [0.4775],
        [0.7564],
        [0.5064]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.5569],
        [0.4739],
        [0.7083],
        [0.4753]], device='cuda:0')
tensor([[-0.0200, -0.0088, -0.0224,  ..., -0.0197, -0.0132, -0.0142],
        [-0.0243, -0.011

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0093, -0.0085, -0.0197,  ..., -0.0067, -0.0137, -0.0107],
        [ 0.0129, -0.0093, -0.0340,  ..., -0.0351, -0.0178, -0.0147],
        [-0.0182, -0.0095, -0.0217,  ..., -0.0143, -0.0129, -0.0131],
        [-0.0200, -0.0116, -0.0256,  ..., -0.0188, -0.0146, -0.0109]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0236, -0.0254,  0.0500,  ..., -0.0284, -0.0122, -0.0330],
        [-0.0364, -0.0325, -0.0057,  ..., -0.0297,  0.0220, -0.0392],
        [-0.0125, -0.0206,  0.0081,  ..., -0.0147, -0.0017, -0.0210],
        [-0.0105, -0.0200,  0.0065,  ..., -0.0148,  0.0120, -0.0213]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.9172],
        [0.1267],
        [0.6039],
        [0.4963]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.9472],
        [0.1583],
        [0.6061],
        [0.4683]], device='cuda:0')
tensor([[-0.0199, -0.0114, -0.0311,  ..., -0.0215, -0.0139, -0.0106],
        [-0.0161, -0.012

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0295, -0.0121, -0.0255,  ..., -0.0292, -0.0142, -0.0112],
        [-0.0206, -0.0116, -0.0137,  ..., -0.0180, -0.0144, -0.0068],
        [-0.0231, -0.0137, -0.0273,  ..., -0.0242, -0.0142, -0.0074],
        [-0.0198, -0.0102, -0.0253,  ..., -0.0183, -0.0136, -0.0128]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0087, -0.0230, -0.0038,  ..., -0.0165,  0.0159, -0.0211],
        [-0.0099, -0.0180,  0.0077,  ..., -0.0148, -0.0043, -0.0214],
        [-0.0054, -0.0184,  0.0071,  ..., -0.0115,  0.0104, -0.0225],
        [-0.0096, -0.0198,  0.0116,  ..., -0.0117,  0.0040, -0.0195]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4445],
        [0.5999],
        [0.5267],
        [0.5413]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4753],
        [0.6569],
        [0.5381],
        [0.6061]], device='cuda:0')
tensor([[-0.0237, -0.0114, -0.0128,  ..., -0.0106, -0.0157, -0.0101],
        [-0.0025, -0.011

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0083, -0.0108, -0.0416,  ..., -0.0453, -0.0175, -0.0156],
        [-0.0218, -0.0094, -0.0326,  ..., -0.0264, -0.0157, -0.0138],
        [-0.0136, -0.0093, -0.0362,  ..., -0.0180, -0.0157, -0.0121],
        [-0.0196, -0.0116, -0.0160,  ..., -0.0182, -0.0148, -0.0094]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0201, -0.0281, -0.0049,  ..., -0.0195,  0.0180, -0.0226],
        [-0.0091, -0.0213,  0.0026,  ..., -0.0140,  0.0142, -0.0211],
        [-0.0076, -0.0209,  0.0079,  ..., -0.0145,  0.0097, -0.0216],
        [-0.0125, -0.0193,  0.0170,  ..., -0.0182, -0.0167, -0.0267]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.3676],
        [0.4539],
        [0.4863],
        [0.7298]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.3944],
        [0.4531],
        [0.5375],
        [0.6569]], device='cuda:0')
tensor([[-0.0145, -0.0090, -0.0331,  ..., -0.0228, -0.0156, -0.0116],
        [-0.0163, -0.009

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0199, -0.0119, -0.0262,  ..., -0.0376, -0.0159, -0.0153],
        [-0.0163, -0.0105, -0.0211,  ..., -0.0220, -0.0147, -0.0124],
        [-0.0087, -0.0080, -0.0249,  ..., -0.0160, -0.0147, -0.0166],
        [-0.0141, -0.0109, -0.0407,  ..., -0.0483, -0.0195, -0.0172]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0079, -0.0189,  0.0070,  ..., -0.0131,  0.0104, -0.0214],
        [-0.0194, -0.0223,  0.0373,  ..., -0.0355, -0.0233, -0.0307],
        [-0.0207, -0.0291,  0.0276,  ..., -0.0293, -0.0180, -0.0227],
        [-0.0181, -0.0272, -0.0091,  ..., -0.0150,  0.0090, -0.0269]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5086],
        [0.8855],
        [0.8508],
        [0.3681]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4611],
        [0.9861],
        [0.7500],
        [0.3750]], device='cuda:0')
tensor([[-0.0227, -0.0111, -0.0244,  ..., -0.0361, -0.0148, -0.0106],
        [-0.0120, -0.009

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0127, -0.0095, -0.0333,  ..., -0.0370, -0.0161, -0.0109],
        [-0.0238, -0.0116, -0.0246,  ..., -0.0357, -0.0138, -0.0105],
        [-0.0111, -0.0086, -0.0249,  ..., -0.0187, -0.0141, -0.0166],
        [-0.0247, -0.0113, -0.0238,  ..., -0.0321, -0.0136, -0.0101]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0077, -0.0220,  0.0070,  ..., -0.0130,  0.0102, -0.0212],
        [-0.0102, -0.0189,  0.0029,  ..., -0.0164,  0.0101, -0.0229],
        [-0.0106, -0.0252,  0.0140,  ..., -0.0165, -0.0160, -0.0210],
        [-0.0073, -0.0211,  0.0043,  ..., -0.0160,  0.0112, -0.0228]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5047],
        [0.4514],
        [0.6187],
        [0.4739]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4531],
        [0.4692],
        [0.7500],
        [0.4753]], device='cuda:0')
tensor([[-0.0083, -0.0092, -0.0228,  ..., -0.0110, -0.0105, -0.0122],
        [-0.0173, -0.012

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-1.0275e-02, -9.0518e-03, -3.3103e-02,  ..., -2.7786e-02,
         -1.3263e-02, -1.5128e-02],
        [-2.0781e-02, -9.4493e-03, -3.7916e-02,  ..., -4.3162e-02,
         -1.6190e-02, -1.0645e-02],
        [-1.1742e-02, -9.1730e-03, -2.4973e-02,  ..., -1.3225e-02,
         -1.0257e-02, -1.1220e-02],
        [-2.0919e-05, -9.9921e-03, -2.4474e-02,  ..., -1.2559e-02,
         -1.5574e-02, -9.8130e-03]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0292, -0.0310, -0.0173,  ..., -0.0208,  0.0314, -0.0261],
        [-0.0134, -0.0233,  0.0053,  ..., -0.0152,  0.0141, -0.0213],
        [-0.0139, -0.0273,  0.0194,  ..., -0.0189, -0.0129, -0.0275],
        [-0.0274, -0.0211,  0.0364,  ..., -0.0344, -0.0224, -0.0307]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.2480],
        [0.4219],
        [0.8445],
        [0.9441]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.2750],
        [0.4247],
        [0.7611],
     

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0226, -0.0114, -0.0370,  ..., -0.0390, -0.0177, -0.0108],
        [-0.0101, -0.0100, -0.0260,  ..., -0.0179, -0.0162, -0.0137],
        [-0.0192, -0.0114, -0.0181,  ..., -0.0268, -0.0131, -0.0113],
        [-0.0158, -0.0100, -0.0355,  ..., -0.0490, -0.0165, -0.0141]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0070, -0.0210,  0.0063,  ..., -0.0146,  0.0096, -0.0215],
        [-0.0300, -0.0304,  0.0474,  ..., -0.0310, -0.0301, -0.0387],
        [-0.0067, -0.0203,  0.0085,  ..., -0.0133,  0.0066, -0.0221],
        [-0.0328, -0.0427, -0.0121,  ..., -0.0283,  0.0285, -0.0454]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4795],
        [1.0327],
        [0.5186],
        [0.2191]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4806],
        [0.9472],
        [0.5103],
        [0.2556]], device='cuda:0')
tensor([[-0.0198, -0.0101, -0.0362,  ..., -0.0346, -0.0164, -0.0103],
        [-0.0253, -0.010

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0124, -0.0096, -0.0216,  ..., -0.0074, -0.0137, -0.0127],
        [ 0.0148, -0.0110, -0.0337,  ..., -0.0586, -0.0188, -0.0167],
        [-0.0239, -0.0107, -0.0265,  ..., -0.0430, -0.0164, -0.0080],
        [-0.0158, -0.0110, -0.0342,  ..., -0.0497, -0.0158, -0.0134]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0336, -0.0203,  0.0319,  ..., -0.0256, -0.0165, -0.0250],
        [-0.0485, -0.0429, -0.0328,  ..., -0.0378,  0.0025, -0.0334],
        [-0.0077, -0.0221,  0.0096,  ..., -0.0126,  0.0110, -0.0218],
        [-0.0126, -0.0295, -0.0054,  ..., -0.0188,  0.0106, -0.0271]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.9844],
        [0.1573],
        [0.4884],
        [0.3843]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.9444],
        [0.1583],
        [0.5078],
        [0.4028]], device='cuda:0')
tensor([[-0.0124, -0.0105, -0.0313,  ..., -0.0380, -0.0175, -0.0158],
        [-0.0165, -0.010

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0162, -0.0106, -0.0412,  ..., -0.0533, -0.0202, -0.0196],
        [-0.0250, -0.0117, -0.0275,  ..., -0.0553, -0.0173, -0.0067],
        [-0.0183, -0.0114, -0.0231,  ..., -0.0364, -0.0142, -0.0140],
        [ 0.0215, -0.0104, -0.0401,  ..., -0.0677, -0.0214, -0.0192]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0295, -0.0266, -0.0090,  ..., -0.0218,  0.0005, -0.0281],
        [-0.0071, -0.0204,  0.0055,  ..., -0.0138,  0.0097, -0.0234],
        [-0.0078, -0.0226,  0.0080,  ..., -0.0130,  0.0103, -0.0203],
        [-0.0440, -0.0523, -0.0314,  ..., -0.0365,  0.0194, -0.0288]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.3629],
        [0.5247],
        [0.4826],
        [0.1377]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.3678],
        [0.5056],
        [0.4611],
        [0.1583]], device='cuda:0')
tensor([[-0.0276, -0.0109, -0.0337,  ..., -0.0387, -0.0173, -0.0139],
        [-0.0219, -0.011

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0304, -0.0114, -0.0220,  ..., -0.0283, -0.0125, -0.0095],
        [-0.0156, -0.0113, -0.0217,  ..., -0.0326, -0.0136, -0.0133],
        [-0.0265, -0.0092, -0.0283,  ..., -0.0286, -0.0138, -0.0181],
        [-0.0216, -0.0088, -0.0151,  ..., -0.0150, -0.0120, -0.0088]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0087, -0.0229,  0.0028,  ..., -0.0158,  0.0066, -0.0212],
        [-0.0127, -0.0252,  0.0007,  ..., -0.0148,  0.0070, -0.0207],
        [-0.0102, -0.0226,  0.0220,  ..., -0.0307, -0.0116, -0.0305],
        [-0.0082, -0.0218,  0.0127,  ..., -0.0137,  0.0003, -0.0252]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4397],
        [0.4215],
        [0.7936],
        [0.5733]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4692],
        [0.4611],
        [0.7083],
        [0.5806]], device='cuda:0')
tensor([[-0.0229, -0.0099, -0.0178,  ..., -0.0300, -0.0139, -0.0155],
        [-0.0161, -0.008

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0198, -0.0097, -0.0197,  ..., -0.0192, -0.0126, -0.0132],
        [-0.0129, -0.0086, -0.0247,  ..., -0.0160, -0.0150, -0.0171],
        [-0.0164, -0.0105, -0.0196,  ..., -0.0061, -0.0126, -0.0121],
        [-0.0125, -0.0102, -0.0315,  ..., -0.0477, -0.0154, -0.0110]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0080, -0.0209,  0.0112,  ..., -0.0126,  0.0043, -0.0221],
        [-0.0159, -0.0256,  0.0191,  ..., -0.0254, -0.0328, -0.0255],
        [-0.0122, -0.0226,  0.0136,  ..., -0.0201, -0.0110, -0.0283],
        [-0.0159, -0.0251,  0.0018,  ..., -0.0164,  0.0027, -0.0208]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5414],
        [0.7647],
        [0.6867],
        [0.4041]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4972],
        [0.7500],
        [0.6806],
        [0.4028]], device='cuda:0')
tensor([[-0.0285, -0.0108, -0.0110,  ..., -0.0153, -0.0142, -0.0125],
        [-0.0238, -0.010

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0246, -0.0124, -0.0315,  ..., -0.0506, -0.0181, -0.0075],
        [-0.0175, -0.0144, -0.0368,  ..., -0.0446, -0.0157, -0.0164],
        [-0.0172, -0.0123, -0.0444,  ..., -0.0368, -0.0165, -0.0116],
        [-0.0194, -0.0137, -0.0327,  ..., -0.0411, -0.0146, -0.0112]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0056, -0.0202,  0.0080,  ..., -0.0133,  0.0060, -0.0224],
        [-0.0138, -0.0294, -0.0078,  ..., -0.0182,  0.0116, -0.0232],
        [-0.0129, -0.0250,  0.0017,  ..., -0.0161,  0.0037, -0.0227],
        [-0.0168, -0.0256, -0.0009,  ..., -0.0194,  0.0151, -0.0271]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4961],
        [0.3684],
        [0.4635],
        [0.3985]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.5078],
        [0.3417],
        [0.4683],
        [0.3642]], device='cuda:0')
tensor([[-0.0250, -0.0120, -0.0330,  ..., -0.0342, -0.0137, -0.0136],
        [-0.0208, -0.009

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0155, -0.0093, -0.0412,  ..., -0.0455, -0.0166, -0.0133],
        [-0.0148, -0.0115, -0.0459,  ..., -0.0735, -0.0201, -0.0131],
        [-0.0162, -0.0108, -0.0218,  ..., -0.0199, -0.0141, -0.0133],
        [-0.0284, -0.0117, -0.0298,  ..., -0.0290, -0.0148, -0.0149]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0185, -0.0300, -0.0009,  ..., -0.0136,  0.0039, -0.0266],
        [-0.0189, -0.0241, -0.0142,  ..., -0.0206, -0.0041, -0.0305],
        [-0.0217, -0.0249,  0.0222,  ..., -0.0265, -0.0303, -0.0366],
        [-0.0076, -0.0231,  0.0043,  ..., -0.0178, -0.0108, -0.0216]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4050],
        [0.4079],
        [0.9695],
        [0.6127]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4172],
        [0.4028],
        [0.9861],
        [0.6061]], device='cuda:0')
tensor([[-0.0189, -0.0101, -0.0349,  ..., -0.0345, -0.0168, -0.0128],
        [-0.0158, -0.011

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0060, -0.0092, -0.0374,  ..., -0.0299, -0.0130, -0.0174],
        [-0.0208, -0.0131, -0.0218,  ..., -0.0236, -0.0145, -0.0100],
        [-0.0156, -0.0092, -0.0370,  ..., -0.0419, -0.0174, -0.0127],
        [-0.0264, -0.0113, -0.0140,  ..., -0.0192, -0.0142, -0.0158]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0283, -0.0288, -0.0141,  ..., -0.0174,  0.0105, -0.0263],
        [-0.0055, -0.0187,  0.0108,  ..., -0.0163, -0.0033, -0.0204],
        [-0.0122, -0.0246, -0.0111,  ..., -0.0142,  0.0024, -0.0229],
        [-0.0092, -0.0229,  0.0079,  ..., -0.0159, -0.0141, -0.0269]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.3182],
        [0.5787],
        [0.3723],
        [0.5999]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.2750],
        [0.5717],
        [0.3678],
        [0.6669]], device='cuda:0')
tensor([[-0.0122, -0.0105, -0.0355,  ..., -0.0284, -0.0127, -0.0159],
        [-0.0221, -0.010

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0022, -0.0108, -0.0222,  ..., -0.0142, -0.0149, -0.0103],
        [-0.0197, -0.0133, -0.0254,  ..., -0.0222, -0.0130, -0.0085],
        [-0.0142, -0.0131, -0.0295,  ..., -0.0324, -0.0140, -0.0156],
        [-0.0166, -0.0075, -0.0389,  ..., -0.0398, -0.0153, -0.0215]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0222, -0.0301,  0.0304,  ..., -0.0293, -0.0261, -0.0328],
        [-0.0082, -0.0206,  0.0076,  ..., -0.0135,  0.0053, -0.0223],
        [-0.0172, -0.0247, -0.0160,  ..., -0.0165,  0.0135, -0.0313],
        [-0.0342, -0.0422, -0.0176,  ..., -0.0222,  0.0709, -0.0281]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.9434],
        [0.5193],
        [0.3137],
        [0.0621]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.9417],
        [0.5381],
        [0.3417],
        [0.0694]], device='cuda:0')
tensor([[-0.0154, -0.0102, -0.0347,  ..., -0.0404, -0.0164, -0.0146],
        [-0.0180, -0.012

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0216, -0.0109, -0.0356,  ..., -0.0393, -0.0185, -0.0162],
        [ 0.0184, -0.0115, -0.0417,  ..., -0.0759, -0.0213, -0.0200],
        [-0.0290, -0.0105, -0.0337,  ..., -0.0502, -0.0194, -0.0143],
        [-0.0168, -0.0079, -0.0308,  ..., -0.0290, -0.0144, -0.0163]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0068, -0.0204,  0.0055,  ..., -0.0141, -0.0006, -0.0231],
        [-0.0389, -0.0391, -0.0326,  ..., -0.0257, -0.0032, -0.0285],
        [-0.0087, -0.0208,  0.0018,  ..., -0.0140,  0.0092, -0.0236],
        [-0.0207, -0.0203,  0.0125,  ..., -0.0157, -0.0123, -0.0302]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5460],
        [0.1974],
        [0.4796],
        [0.7226]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.5778],
        [0.1583],
        [0.4739],
        [0.8167]], device='cuda:0')
tensor([[-0.0292, -0.0095, -0.0184,  ..., -0.0539, -0.0174, -0.0070],
        [-0.0277, -0.011

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0159, -0.0101, -0.0313,  ..., -0.0269, -0.0158, -0.0130],
        [-0.0193, -0.0128, -0.0239,  ..., -0.0273, -0.0152, -0.0082],
        [-0.0141, -0.0104, -0.0197,  ..., -0.0126, -0.0126, -0.0119],
        [-0.0184, -0.0126, -0.0367,  ..., -0.0295, -0.0141, -0.0099]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-8.5692e-03, -2.0168e-02,  8.3068e-03,  ..., -1.2957e-02,
         -4.2117e-05, -2.1003e-02],
        [-9.6270e-03, -2.1258e-02,  7.8568e-03,  ..., -1.4263e-02,
          1.2406e-03, -2.2665e-02],
        [-1.9874e-02, -3.0667e-02,  3.1330e-02,  ..., -2.7196e-02,
         -3.3639e-02, -3.1451e-02],
        [-2.3001e-02, -2.6227e-02, -2.5931e-03,  ..., -1.5832e-02,
          4.7264e-03, -2.1334e-02]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5527],
        [0.5747],
        [0.9451],
        [0.4229]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.5778],
        [0.5717],
        [0.9861],
     

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0223, -0.0105, -0.0217,  ..., -0.0305, -0.0137, -0.0114],
        [-0.0128, -0.0070, -0.0439,  ..., -0.0499, -0.0169, -0.0271],
        [-0.0131, -0.0102, -0.0364,  ..., -0.0472, -0.0157, -0.0131],
        [-0.0244, -0.0132, -0.0232,  ..., -0.0316, -0.0127, -0.0156]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0120, -0.0211,  0.0075,  ..., -0.0151,  0.0062, -0.0225],
        [-0.0374, -0.0475, -0.0267,  ..., -0.0225,  0.0776, -0.0179],
        [-0.0380, -0.0314, -0.0150,  ..., -0.0241,  0.0138, -0.0242],
        [-0.0141, -0.0215,  0.0083,  ..., -0.0184, -0.0159, -0.0200]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4629],
        [0.0910],
        [0.2712],
        [0.6012]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4972],
        [0.0694],
        [0.2556],
        [0.5861]], device='cuda:0')
tensor([[-0.0122, -0.0100, -0.0315,  ..., -0.0362, -0.0131, -0.0134],
        [-0.0146, -0.013

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0225, -0.0141, -0.0286,  ..., -0.0653, -0.0199, -0.0122],
        [-0.0230, -0.0109, -0.0371,  ..., -0.0360, -0.0170, -0.0145],
        [-0.0131, -0.0105, -0.0320,  ..., -0.0312, -0.0166, -0.0126],
        [-0.0119, -0.0104, -0.0340,  ..., -0.0309, -0.0167, -0.0118]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0185, -0.0239, -0.0037,  ..., -0.0176,  0.0014, -0.0205],
        [-0.0145, -0.0215,  0.0060,  ..., -0.0128,  0.0082, -0.0199],
        [-0.0065, -0.0201,  0.0100,  ..., -0.0124,  0.0067, -0.0224],
        [-0.0064, -0.0202,  0.0092,  ..., -0.0116,  0.0067, -0.0224]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.3897],
        [0.4410],
        [0.5225],
        [0.5033]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4456],
        [0.4531],
        [0.5178],
        [0.5278]], device='cuda:0')
tensor([[-0.0188, -0.0134, -0.0290,  ..., -0.0303, -0.0132, -0.0070],
        [-0.0105, -0.012

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0150, -0.0106, -0.0336,  ..., -0.0320, -0.0160, -0.0112],
        [-0.0081, -0.0091, -0.0274,  ..., -0.0142, -0.0129, -0.0097],
        [-0.0134, -0.0094, -0.0339,  ..., -0.0283, -0.0149, -0.0117],
        [-0.0150, -0.0116, -0.0302,  ..., -0.0233, -0.0139, -0.0077]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0083, -0.0219,  0.0046,  ..., -0.0142,  0.0086, -0.0215],
        [-0.0078, -0.0225,  0.0125,  ..., -0.0144,  0.0020, -0.0220],
        [-0.0080, -0.0216,  0.0112,  ..., -0.0132,  0.0062, -0.0215],
        [-0.0171, -0.0231, -0.0042,  ..., -0.0203,  0.0117, -0.0217]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5133],
        [0.5802],
        [0.5388],
        [0.3996]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4806],
        [0.5475],
        [0.5142],
        [0.4497]], device='cuda:0')
tensor([[-1.1922e-02, -1.1926e-02, -3.2668e-02,  ..., -3.5444e-02,
         -1.3170e-02, -1.08

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0231, -0.0109, -0.0423,  ..., -0.0472, -0.0179, -0.0164],
        [-0.0107, -0.0066, -0.0426,  ..., -0.0453, -0.0152, -0.0251],
        [-0.0135, -0.0119, -0.0377,  ..., -0.0482, -0.0155, -0.0150],
        [-0.0004, -0.0105, -0.0412,  ..., -0.0545, -0.0213, -0.0172]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0166, -0.0212,  0.0073,  ..., -0.0175,  0.0114, -0.0258],
        [-0.0334, -0.0418, -0.0037,  ..., -0.0278,  0.0782, -0.0190],
        [-0.0253, -0.0315,  0.0005,  ..., -0.0157, -0.0012, -0.0289],
        [-0.0204, -0.0231, -0.0037,  ..., -0.0207,  0.0109, -0.0297]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4513],
        [0.0541],
        [0.3824],
        [0.3727]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4531],
        [0.0694],
        [0.3642],
        [0.3678]], device='cuda:0')
tensor([[-0.0036, -0.0115, -0.0366,  ..., -0.0628, -0.0180, -0.0171],
        [-0.0080, -0.009

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0201, -0.0101, -0.0175,  ..., -0.0271, -0.0135, -0.0133],
        [-0.0116, -0.0086, -0.0332,  ..., -0.0267, -0.0140, -0.0153],
        [-0.0275, -0.0108, -0.0369,  ..., -0.0440, -0.0171, -0.0142],
        [-0.0213, -0.0113, -0.0294,  ..., -0.0535, -0.0188, -0.0090]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0109, -0.0220,  0.0134,  ..., -0.0137,  0.0055, -0.0223],
        [-0.0208, -0.0288,  0.0252,  ..., -0.0275, -0.0275, -0.0320],
        [-0.0132, -0.0240,  0.0025,  ..., -0.0130,  0.0077, -0.0169],
        [-0.0104, -0.0206,  0.0086,  ..., -0.0138,  0.0072, -0.0226]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4826],
        [0.7773],
        [0.4424],
        [0.4869]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4972],
        [0.8167],
        [0.4531],
        [0.5106]], device='cuda:0')
tensor([[-0.0216, -0.0113, -0.0339,  ..., -0.0373, -0.0115, -0.0135],
        [-0.0228, -0.011

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0209, -0.0095, -0.0176,  ..., -0.0279, -0.0132, -0.0106],
        [-0.0174, -0.0066, -0.0366,  ..., -0.0452, -0.0143, -0.0194],
        [-0.0098, -0.0089, -0.0196,  ..., -0.0130, -0.0145, -0.0137],
        [-0.0285, -0.0122, -0.0208,  ..., -0.0256, -0.0123, -0.0126]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0117, -0.0196,  0.0124,  ..., -0.0158,  0.0012, -0.0219],
        [-0.0410, -0.0429, -0.0130,  ..., -0.0152,  0.0773, -0.0314],
        [-0.0225, -0.0228,  0.0322,  ..., -0.0307, -0.0314, -0.0367],
        [-0.0130, -0.0214,  0.0116,  ..., -0.0150, -0.0072, -0.0232]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5903],
        [0.0817],
        [0.9030],
        [0.6146]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.5806],
        [0.0694],
        [0.9472],
        [0.6250]], device='cuda:0')
tensor([[-0.0214, -0.0131, -0.0286,  ..., -0.0382, -0.0144, -0.0186],
        [-0.0175, -0.009

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0120, -0.0088, -0.0319,  ..., -0.0240, -0.0126, -0.0118],
        [-0.0251, -0.0116, -0.0232,  ..., -0.0345, -0.0125, -0.0102],
        [-0.0203, -0.0121, -0.0365,  ..., -0.0473, -0.0150, -0.0110],
        [-0.0154, -0.0096, -0.0213,  ..., -0.0157, -0.0121, -0.0120]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0215, -0.0258,  0.0053,  ..., -0.0144,  0.0151, -0.0233],
        [-0.0111, -0.0225,  0.0098,  ..., -0.0173,  0.0079, -0.0242],
        [-0.0249, -0.0235,  0.0136,  ..., -0.0176,  0.0094, -0.0261],
        [-0.0162, -0.0234,  0.0285,  ..., -0.0256, -0.0177, -0.0364]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.3065],
        [0.5124],
        [0.3860],
        [0.8762]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.2750],
        [0.4692],
        [0.3750],
        [0.9861]], device='cuda:0')
tensor([[-0.0153, -0.0102, -0.0286,  ..., -0.0340, -0.0152, -0.0107],
        [-0.0224, -0.009

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0200, -0.0103, -0.0317,  ..., -0.0222, -0.0159, -0.0137],
        [-0.0286, -0.0120, -0.0234,  ..., -0.0305, -0.0132, -0.0095],
        [-0.0275, -0.0116, -0.0233,  ..., -0.0453, -0.0165, -0.0049],
        [-0.0248, -0.0105, -0.0378,  ..., -0.0424, -0.0154, -0.0130]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0076, -0.0210,  0.0092,  ..., -0.0144, -0.0048, -0.0210],
        [-0.0122, -0.0221,  0.0041,  ..., -0.0160,  0.0036, -0.0219],
        [-0.0091, -0.0200,  0.0103,  ..., -0.0149,  0.0091, -0.0222],
        [-0.0151, -0.0222,  0.0128,  ..., -0.0140,  0.0111, -0.0246]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.6247],
        [0.4626],
        [0.5109],
        [0.4613]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.5778],
        [0.4692],
        [0.5106],
        [0.4747]], device='cuda:0')
tensor([[-0.0183, -0.0106, -0.0299,  ..., -0.0290, -0.0154, -0.0118],
        [-0.0245, -0.011

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0216, -0.0126, -0.0259,  ..., -0.0328, -0.0133, -0.0115],
        [-0.0249, -0.0116, -0.0347,  ..., -0.0294, -0.0141, -0.0095],
        [-0.0150, -0.0096, -0.0300,  ..., -0.0280, -0.0152, -0.0101],
        [-0.0314, -0.0121, -0.0245,  ..., -0.0291, -0.0142, -0.0115]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0188, -0.0275,  0.0115,  ..., -0.0177,  0.0044, -0.0238],
        [-0.0092, -0.0226,  0.0117,  ..., -0.0143,  0.0112, -0.0198],
        [-0.0089, -0.0206,  0.0121,  ..., -0.0138,  0.0076, -0.0216],
        [-0.0108, -0.0220,  0.0127,  ..., -0.0173,  0.0083, -0.0248]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4184],
        [0.4973],
        [0.5579],
        [0.4445]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4503],
        [0.5128],
        [0.5278],
        [0.4753]], device='cuda:0')
tensor([[-0.0248, -0.0100, -0.0385,  ..., -0.0323, -0.0146, -0.0107],
        [-0.0227, -0.011

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0233, -0.0106, -0.0175,  ..., -0.0190, -0.0132, -0.0068],
        [-0.0221, -0.0126, -0.0224,  ..., -0.0225, -0.0146, -0.0075],
        [-0.0291, -0.0105, -0.0314,  ..., -0.0285, -0.0121, -0.0130],
        [-0.0251, -0.0099, -0.0368,  ..., -0.0309, -0.0137, -0.0095]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0093, -0.0207,  0.0125,  ..., -0.0140, -0.0030, -0.0239],
        [-0.0104, -0.0205,  0.0132,  ..., -0.0157, -0.0007, -0.0246],
        [-0.0078, -0.0191,  0.0091,  ..., -0.0140,  0.0008, -0.0225],
        [-0.0059, -0.0199,  0.0096,  ..., -0.0129,  0.0065, -0.0214]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5783],
        [0.5511],
        [0.5601],
        [0.5129]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.5806],
        [0.5717],
        [0.5569],
        [0.5375]], device='cuda:0')
tensor([[-0.0188, -0.0089, -0.0356,  ..., -0.0450, -0.0189, -0.0147],
        [-0.0159, -0.010

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0220, -0.0116, -0.0349,  ..., -0.0266, -0.0152, -0.0110],
        [-0.0233, -0.0108, -0.0362,  ..., -0.0366, -0.0162, -0.0121],
        [-0.0238, -0.0125, -0.0328,  ..., -0.0259, -0.0151, -0.0101],
        [-0.0182, -0.0110, -0.0336,  ..., -0.0268, -0.0166, -0.0126]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0103, -0.0219,  0.0119,  ..., -0.0151,  0.0095, -0.0198],
        [-0.0087, -0.0204,  0.0116,  ..., -0.0145,  0.0083, -0.0230],
        [-0.0226, -0.0257,  0.0110,  ..., -0.0201,  0.0077, -0.0223],
        [-0.0089, -0.0205,  0.0099,  ..., -0.0153, -0.0002, -0.0220]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5078],
        [0.5078],
        [0.4507],
        [0.6183]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.5000],
        [0.5094],
        [0.4497],
        [0.5778]], device='cuda:0')
tensor([[-0.0155, -0.0122, -0.0426,  ..., -0.0434, -0.0180, -0.0172],
        [-0.0229, -0.010

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0169, -0.0101, -0.0172,  ..., -0.0512, -0.0191, -0.0130],
        [-0.0102, -0.0094, -0.0256,  ..., -0.0098, -0.0158, -0.0134],
        [-0.0139, -0.0087, -0.0420,  ..., -0.0446, -0.0175, -0.0130],
        [-0.0178, -0.0099, -0.0209,  ..., -0.0233, -0.0132, -0.0119]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0090, -0.0218,  0.0101,  ..., -0.0178, -0.0167, -0.0225],
        [-0.0221, -0.0210,  0.0171,  ..., -0.0334, -0.0256, -0.0338],
        [-0.0227, -0.0234,  0.0060,  ..., -0.0141,  0.0105, -0.0285],
        [-0.0114, -0.0209,  0.0124,  ..., -0.0143,  0.0077, -0.0221]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.6445],
        [1.0382],
        [0.3643],
        [0.4813]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.6278],
        [0.9444],
        [0.4247],
        [0.4972]], device='cuda:0')
tensor([[-0.0257, -0.0128, -0.0197,  ..., -0.0273, -0.0128, -0.0121],
        [-0.0091, -0.011

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0157, -0.0103, -0.0259,  ..., -0.0263, -0.0159, -0.0086],
        [-0.0090, -0.0107, -0.0370,  ..., -0.0560, -0.0164, -0.0196],
        [-0.0116, -0.0117, -0.0411,  ..., -0.0434, -0.0185, -0.0179],
        [-0.0113, -0.0092, -0.0271,  ..., -0.0342, -0.0138, -0.0142]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-6.9259e-03, -1.9387e-02,  7.9763e-03,  ..., -1.1510e-02,
         -1.2701e-05, -2.2408e-02],
        [-2.5853e-02, -2.8372e-02, -7.2682e-04,  ..., -1.8656e-02,
         -4.4961e-04, -2.4064e-02],
        [-3.8095e-02, -4.0041e-02, -2.3357e-03,  ..., -2.5315e-02,
          5.2142e-02, -2.9824e-02],
        [-1.0401e-02, -2.1471e-02,  9.3867e-03,  ..., -2.2683e-02,
         -5.9245e-03, -2.1392e-02]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.5418],
        [0.3841],
        [0.0941],
        [0.7064]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.5639],
        [0.4028],
        [0.0917],
     

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0215, -0.0103, -0.0139,  ..., -0.0176, -0.0139, -0.0117],
        [-0.0104, -0.0091, -0.0254,  ..., -0.0186, -0.0149, -0.0172],
        [-0.0189, -0.0090, -0.0175,  ..., -0.0194, -0.0122, -0.0110],
        [-0.0092, -0.0089, -0.0275,  ..., -0.0291, -0.0151, -0.0111]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0099, -0.0210,  0.0098,  ..., -0.0202, -0.0184, -0.0201],
        [-0.0154, -0.0248,  0.0133,  ..., -0.0220, -0.0238, -0.0244],
        [-0.0103, -0.0205,  0.0086,  ..., -0.0156,  0.0044, -0.0209],
        [-0.0075, -0.0197,  0.0083,  ..., -0.0150,  0.0058, -0.0214]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.6309],
        [0.7493],
        [0.5159],
        [0.5393]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.6844],
        [0.7500],
        [0.5103],
        [0.5278]], device='cuda:0')
tensor([[-0.0207, -0.0121, -0.0328,  ..., -0.0334, -0.0130, -0.0149],
        [-0.0203, -0.012

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0196, -0.0106, -0.0301,  ..., -0.0266, -0.0127, -0.0093],
        [-0.0230, -0.0105, -0.0139,  ..., -0.0100, -0.0125, -0.0089],
        [-0.0085, -0.0112, -0.0382,  ..., -0.0537, -0.0174, -0.0158],
        [-0.0164, -0.0091, -0.0191,  ..., -0.0108, -0.0119, -0.0110]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0157, -0.0206,  0.0055,  ..., -0.0152,  0.0035, -0.0189],
        [-0.0135, -0.0218,  0.0126,  ..., -0.0195, -0.0127, -0.0216],
        [-0.0263, -0.0233, -0.0035,  ..., -0.0245,  0.0098, -0.0272],
        [-0.0160, -0.0298,  0.0211,  ..., -0.0297, -0.0327, -0.0240]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.4588],
        [0.6703],
        [0.3603],
        [0.9959]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.4683],
        [0.6669],
        [0.4028],
        [0.9861]], device='cuda:0')
tensor([[-0.0171, -0.0073, -0.0328,  ..., -0.0252, -0.0122, -0.0135],
        [-0.0161, -0.009

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([[-0.0247, -0.0098, -0.0317,  ..., -0.0327, -0.0107, -0.0100],
        [-0.0149, -0.0093, -0.0183,  ..., -0.0056, -0.0124, -0.0117],
        [-0.0201, -0.0089, -0.0243,  ..., -0.0109, -0.0093, -0.0106],
        [-0.0184, -0.0085, -0.0208,  ..., -0.0053, -0.0130, -0.0105]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0238, -0.0232,  0.0045,  ..., -0.0174,  0.0017, -0.0298],
        [-0.0099, -0.0241,  0.0018,  ..., -0.0201, -0.0182, -0.0222],
        [-0.0173, -0.0236,  0.0102,  ..., -0.0280, -0.0140, -0.0276],
        [-0.0284, -0.0268,  0.0330,  ..., -0.0360, -0.0297, -0.0270]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.3986],
        [0.7734],
        [0.7932],
        [0.9222]], device='cuda:0', grad_fn=<AddmmBackward0>) tensor([[0.3833],
        [0.6806],
        [0.7611],
        [0.9444]], device='cuda:0')
tensor([[-0.0228, -0.0107, -0.0278,  ..., -0.0254, -0.0121, -0.0089],
        [-0.0314, -0.011

In [ ]:

def check_accuracy(loader, model, desAcc):
    # if loader.dataset.training:
    #     print('Checking accuracy on training data')
    # else:
    #     print('Checking accuracy on test data')
    index = np.zeros((25,))
    num_correct = 0
    num_samples = 0
    model.eval()
    # i=1
    with torch.no_grad():
        for x, y in loader:
            x = x.to(device=device)
            y = y.to(device=device)
            # x = x.reshape(x.shape[0], -1)
            y = y.reshape(y.shape[0], -1)
            scores = model(x)
            
            # _, predictions = scores.max(1)  # dimension of predictions
            # predictions = torch.argmax(scores, dim=1)
            # new_y = torch.argmax(y, dim=2)
            # _, predictions = scores.max(1)
            # if i<22:
            #   predictions = scores.reshape(4)
            # else:
            #   predictions = scores.reshape(1)
            # i+=1
            predictions = scores.reshape(scores.shape[0], -1)
            # print(predictions, "--", y)
            # print(y)
            # print(desAcc*y)
            num_correct += (torch.abs(predictions - y) < desAcc*y).sum()
            num_samples += predictions.size(0)

        print(f'Got {num_correct} / {num_samples} with accuracy {float(num_correct) / float(num_samples) * 100:.2f} %')
    model.train()

In [ ]:
# check_accuracy(train_loader, model, desAcc = 0.1)
check_accuracy(test_loader, model, desAcc = 0.1)

tensor([[-0.0210, -0.0101, -0.0180,  ..., -0.0275, -0.0140, -0.0141],
        [-0.0217, -0.0093, -0.0165,  ..., -0.0135, -0.0125, -0.0104],
        [-0.0309, -0.0110, -0.0289,  ..., -0.0591, -0.0174, -0.0068],
        [-0.0226, -0.0104, -0.0346,  ..., -0.0443, -0.0169, -0.0066]],
       device='cuda:0')
tensor([[-0.0096, -0.0209,  0.0093,  ..., -0.0146,  0.0062, -0.0215],
        [-0.0163, -0.0219,  0.0131,  ..., -0.0241, -0.0161, -0.0277],
        [-0.0096, -0.0207,  0.0085,  ..., -0.0140,  0.0069, -0.0223],
        [-0.0060, -0.0207,  0.0087,  ..., -0.0136,  0.0031, -0.0225]],
       device='cuda:0')
tensor([[-0.0124, -0.0101, -0.0247,  ..., -0.0220, -0.0142, -0.0095],
        [-0.0099, -0.0084, -0.0396,  ..., -0.0543, -0.0209, -0.0067],
        [-0.0320, -0.0107, -0.0256,  ..., -0.0456, -0.0174, -0.0199],
        [-0.0101, -0.0115, -0.0289,  ..., -0.0367, -0.0151, -0.0170]],
       device='cuda:0')
tensor([[-0.0261, -0.0293,  0.0017,  ..., -0.0217,  0.0095, -0.0267],
        [-0.037

In [ ]:
checkpoint = {'state_dict': model.state_dict(), 'optimizer': optimizer.state_dict()}
save_checkpoint(checkpoint)

..Saving Model..


In [ ]:
for params in model.parameters():
  print(params)

In [ ]:
load_checkpoint(torch.load("/content/drive/MyDrive/data/saved_model.pth.tar"))

In [ ]:
index = np.zeros((28000,))